package main

import (
	"log"

	termii "github.com/Uchencho/go-termii"
)

func main() {

	// Set TERMII_API_KEY, TERMII_URL and TERMII_SENDER_ID as environment variables
	// Ensure TERMII_URL ends with '/'

	req := termii.AutoGeneratedMessageRequest{
		To:  "2347017449747",
		Sms: "Nwa Alozie pon this one", // You do not need to set to the API Key
	}

	client := termii.NewClient()
	resp, err := client.SendAutoGeneratedMessage(req)
	if err != nil {
		log.Fatal("error in sending autogenerated message", err)
		return
	}
	log.Printf("Response : %+v", resp)
}
