package main

import (
	"log"
	"os"

	termii "github.com/Uchencho/go-termii"
)

func main() {

	req := termii.AutoGeneratedMessageRequest{
		To:  "2347017449747",
		Sms: "Nwa Alozie pon this one", // You do not need to set the API Key
	}

	var (
		apiKey   string = os.Getenv("TERMII_API_KEY")
		baseUrl  string = os.Getenv("TERMII_BASE_URL")
		senderId string = os.Getenv("TERMII_SENDER_ID")
	)

	client := termii.NewClient(apiKey, baseUrl, senderId)
	resp, err := client.SendAutoGeneratedMessage(req)
	if err != nil {
		log.Fatal("error in sending autogenerated message", err)
		return
	}
	log.Printf("Response : %+v", resp)
}
