package main

import (
	"log"
	"net/http"
	"os"

	termii "github.com/Uchencho/go-termii"
)

func main() {
	var httpClient *http.Client

	termiiConfig := termii.Config{
		APIKey:   os.Getenv("TERMII_API_KEY"),
		BaseURL:  os.Getenv("TERMII_BASE_URL"),
		SenderID: os.Getenv("TERMII_SENDER_ID"),
	}

	client := termii.NewClient(termiiConfig, httpClient)

	req := termii.AutoGeneratedMessageRequest{
		To:  "2347017449747",
		Sms: "Nwa Alozie pon this one", // You do not need to set the API Key
	}

	resp, err := client.SendAutoGeneratedMessage(req)
	if err != nil {
		log.Fatal("error in sending autogenerated message", err)
		return
	}
	log.Printf("Response : %+v", resp)
}
